# Change these first
owner: iamalexblue # Your GitHub organization or username, where this repository lives
repo: siteuptime # The name of this repository

sites:
  - name: 从今夜白
    url: https://iamalex.blue
  - name: Blue Wonderland
    url: https://ifruit.club
  - name: Music
    url: https://music.iamalex.blue
  - name: metacubexd
    url: https://d.iamalex.blue
  - name: yacd
    url: https://dash.ifruit.club
  - name: sing-box-sub
    url: https://sing-box.ifruit.club
  - name: Notion blog
    url: https://iamalexblue.notion.site
  - name: ChatGPT-Web-Next
    url: https://chat.iamalex.blue
  - name: RSS-Hub
    url: https:/rss-hub.iamalex.blue
  - name: Koo-Reader
    url: https://reader.iamalex.blue
  - name: Status
    url: https://status.iamalex.blue
  


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.iamalex.blue
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/iamalexblue/jsDelivrCDN/blob/c2d136defc0b5299d058230abca71381b450c20b/static/iamalexblue-cover.svg
  name: Web-watch
  introTitle: "**iamalex.blue** uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: 🍋 从今夜白
      href: https://iamalex.blue
    - title: ⌨️ GitHub
      href: https://github.com/iamalexblue
    - title: 💌 Email
      href: mailto:me@ifruit.club

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
